# Generated by Django 3.0.3 on 2020-03-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='city',
            field=models.CharField(default='Nairobi', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='state',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
