# Generated by Django 3.0.3 on 2020-03-09 20:24

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200309_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
