# Generated by Django 3.0.3 on 2020-02-25 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_variationmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
