# Generated by Django 3.0.3 on 2020-03-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200323_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='update_defaults',
            field=models.BooleanField(default=False),
        ),
    ]
